version: '3.7'
services:
  hello-world:
    container_name: com.pacosystems.helloworld
    image: pacosystems/hello-world:latest
    ports:
      - "3000:3000"
    environment:
      # change this to your own value
      - PORT=3000
      # any environment variable you want to pass to the container - these are displayed in the app so are useful for debugging
      - TEST_ITEM=Hello World
    volumes:
      - ./files:/application/files
    build:
      context:
        ./
